platform :ios, ‘7.0‘

target "百思不得姐练习" do
pod 'AFNetworking', '3.1.0'
pod 'SVProgressHUD','2.0.3'
pod 'MJExtension','3.0.10'
pod 'SDWebImage','3.7.6'
pod 'MJRefresh','3.1.0'
pod 'DACircularProgress','2.3.1'
pod 'pop','1.0.9'
pod 'NJKWebViewProgress', '0.2.3'
end